apiVersion: v1
kind: Service
metadata:
  name: ad-exchange
  labels:
    app: ad-exchange
    tier: backend
spec:
  type: LoadBalancer
  ports:
  - port: 9092
    targetPort: 9092
  selector:
    app: ad-exchange
    tier: backend

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ad-exchange
spec:
  selector:
    matchLabels:
      app: ad-exchange
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: ad-exchange
        tier: backend
    spec:
      containers:
      - name: ad-exchange
        image: ad_exchange_mock:0.1
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 9092
        volumeMounts:
          - name: conf
            mountPath: /app/config.yaml
            subPath: config.yaml
            readOnly: false
      volumes:
        - name: conf
          configMap:
            name: ss-config
            defaultMode: 0755