---
apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: ad-exchange
spec:
  selector:
    matchLabels:
      app: ad-exchange
      tier: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: ad-exchange
        tier: backend
    spec:
      containers:
      - name: ad-exchange
        image: cr.yandex/crpd0memv4ev8ejsr73c/ad_exchange_mock
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080