apiVersion: v1
kind: Service
metadata:
  name: app-store
  labels:
    app: app-store
    tier: backend
spec:
  type: LoadBalancer
  ports:
  - port: 9091
    targetPort: 9091
  selector:
    app: app-store
    tier: backend

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-store
spec:
  selector:
    matchLabels:
      app: app-store
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: app-store
        tier: backend
    spec:
      containers:
      - name: app-store
        image: app_store_mock:0.1
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 9091