apiVersion: v1
kind: Service
metadata:
  name: cur-rates
  labels:
    app: cur-rates
    tier: backend
spec:
  type: LoadBalancer
  ports:
  - port: 9093
    targetPort: 9093
  selector:
    app: cur-rates
    tier: backend

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cur-rates
spec:
  selector:
    matchLabels:
      app: cur-rates
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: cur-rates
        tier: backend
    spec:
      containers:
      - name: cur-rates
        image: cur_rates_mock:0.1
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 9093