apiVersion: v1
kind: Service
metadata:
  name: predictor
  labels:
    app: predictor
    tier: backend
spec:
  type: LoadBalancer
  ports:
  - port: 9094
    targetPort: 9094
  selector:
    app: predictor
    tier: backend

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: predictor
spec:
  selector:
    matchLabels:
      app: predictor
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: predictor
        tier: backend
    spec:
      containers:
      - name: predictor
        image: predictor_mock:0.1.1
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 9094
        volumeMounts:
          - name: conf
            mountPath: /app/config.yaml
            subPath: config.yaml
            readOnly: false
      volumes:
        - name: conf
          configMap:
            name: ss-config
            defaultMode: 0755